spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=fycs

spring.jpa.hibernate.ddl-auto=update

jwt.secret=erRdc3LXo9f5ljUCEDTl6xVUFjdX7NwxhDS1LdbPvJY=